# Generated by Django 5.2.4 on 2025-07-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_activityhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityHistory',
        ),
    ]
